### ISSUE TITLE
dynamic module support

### ISSUE THREAD

**Issue by alonbg** [api7/grpc-client-nginx-module#36]
Hi @spacewander 

Can this module be dynamically loaded by nginx ?
If so would it be possible to add the relevant config file ?
Or at least if you can give me a head start and I will take it from there.

Thanks

**Comment by alonbg** [comment]
Jumped too early. Closing

**Comment by spacewander** [comment]
This module uses some hacks in the https://github.com/api7/grpc-client-nginx-module/blob/main/config. I am not sure if it can be compiled as dynamic module and work correctly.
