### ISSUE TITLE
how to use grpc module in apisix which not greate than v2.12.0

### ISSUE THREAD

**Issue by jujiale** [api7/grpc-client-nginx-module#51]
**description:**
@spacewander 
Hello, we use apisix 2.12.0 develop our gateway. that means we modify some apisix v2.12.0 source code. now, we need to add a plugin in our gateway(which depends on apisix v2.12.0), the plugin which cloud send grpc request to our grpc service and the response determine if the client request have auth to visit the upstream service(the upstream service is http service).

  now as I methioned in apisix issue [https://github.com/apache/apisix/commit/9129572f6302300ddeee3f2234393445d8ead781](url)  I could use this module in our gateway to do this. what I do is merge the change [https://github.com/apache/apisix/commit/9129572f6302300ddeee3f2234393445d8ead781](url) in our gateway code. and I make a install for apisix v2.99.0 in order to find the deps that I need to use in our gateway. after installed v2.99.0 in vmvare. I copy **/usr/local/apisix/deps/lib/luarocks/rocks-5.1/grpc-client-nginx-module and /usr/local/apisix/deps/share/lua/5.1/resty/grpc.lua** in our gateway deps. and update our apisix-base version the same as  v2.99.0.

   then I test send a grpc request. the error log appears:
`

    [lua] grpc.lua:22: /usr/local/janus//deps/share/lua/5.1/resty/grpc.lua:60: The gRPC client engine is not initialized. Need to configure 'grpc_client_engine_path' in the nginx.conf. And this library can not be loaded in the init phase.

`

I want to know why such thing happend. should I must obey the procedure which this repoistory "README.md"(I am not familiar with such procedure Q_Q). can I use some other way to use this module in our gateway. such as by copy some deps in our gateway?

hope yours. thanks.

**ENV**
our gateway: depend on apisix v2.12.0 to develop
openresty version: openresty/1.21.4.1
apisix-base:apisix-base-1.21.4.1.2
linux:Linux 3.10.0-957.21.3.el7.x86_64

**Comment by spacewander** [comment]
Have you added `thread_pool grpc-client-nginx-module threads=1;` in the template?
https://github.com/apache/apisix/blob/ea476911ae6ebf5442e99300afc14ccabc8be368/apisix/cli/ngx_tpl.lua#L61

Note that you need to check the README of 0.2.2, as we have done a big refactor between 0.2.2 and 0.3.0

**Comment by jujiale** [comment]
> Have you added `thread_pool grpc-client-nginx-module threads=1;` in the template? https://github.com/apache/apisix/blob/ea476911ae6ebf5442e99300afc14ccabc8be368/apisix/cli/ngx_tpl.lua#L61
> 
> Note that you need to check the README of 0.2.2, as we have done a big refactor between 0.2.2 and 0.3.0

hello, I added `thread_pool grpc-client-nginx-module threads=1;` in the template
the following is my step:

1. we develop our gateway based on apisix v2.12.0. we add some ourself login code in apisix v2.12.0 code. so we need just combine the grpc code in apisix v2.99.0

2. we are now using apisix-base-1.21.4.1.1-0.el7.x86_64.rpm. I update it to apisix-base-1.21.4.1.2-0.el7.x86_64.rpm. I find in apisix v2.99.0 branch. it added grpc.lua. so I install v2.99.0 in my vmvare. and then in /usr/local/apisix/deps/share/lua/5.1/resty/gprc.lua and /usr/local/janus/deps/lib/luarocks/rocks-5.1/grpc-client-nginx-module. I copyed the grpc.lua and grpc-client-nginx-module directory in our gateway's proper location.

3.added thread_pool grpc-client-nginx-module threads=1; in the ngx_tpl.lua

4. start our gateway. the error log is :
`

       [lua] grpc.lua:22: /usr/local/janus//deps/share/lua/5.1/resty/grpc.lua:57: The gRPC client engine is not initialized. Need to configure 'grpc_client_engine_path' in the nginx.conf. And this library can not be loaded in the init phase.
 
`

and I find the error occurs in resty.grpc the following code:
`

       if C.ngx_http_grpc_cli_is_engine_inited() == 0 then
        error("The gRPC client engine is not initialized. " ..
              "Need to configure 'grpc_client_engine_path' in the nginx.conf. " ..
              "And this library can not be loaded in the init phase."
              )
    end

`
so I guess **C.ngx_http_grpc_cli_is_engine_inited() == 0** is true.

as I mentioned. the question become: how could I use grpc in lower apisix version. such as 2.12.0

hope your help. thx

**Comment by spacewander** [comment]
Maybe you can use gdb to figure out why `gccf->engine` is NULL:
https://github.com/api7/grpc-client-nginx-module/blob/7c14b77437e56ef24d6e729ee0c6177d72c2d27d/src/ngx_http_grpc_client.c#L659

Or upgrade to APISIX 2.99 directly.

**Comment by jujiale** [comment]
> Maybe you can use gdb to figure out why `gccf->engine` is NULL:
> 
> https://github.com/api7/grpc-client-nginx-module/blob/7c14b77437e56ef24d6e729ee0c6177d72c2d27d/src/ngx_http_grpc_client.c#L659
> 
> Or upgrade to APISIX 2.99 directly.

OK. THX
by the way. in apisix-base. this repo following code
`

    ./configure ... \
            --with-threads \
            --with-cc-opt="-DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/path/to/libgrpc_engine.so" \
            --add-module=/path/to/grpc-client-nginx-module

`

**-DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/path/to/libgrpc_engine.so** is refered to "/usr/local/openresty/libgrpc_engine.so"?

**Comment by jujiale** [comment]
I use openresty -V have found that -DNGX_HTTP_GRPC_CLI_ENGINE_PATH=/path/to/libgrpc_engine.so is refered to "/usr/local/openresty/libgrpc_engine.so"

I will try other ways to solve the problem. thx

**Comment by jujiale** [comment]
been resolved, thanks
