### ISSUE TITLE
upgrade grpc-go client library to fix panic issue

### ISSUE THREAD

**Issue by Revolyssup** [api7/grpc-client-nginx-module#69]
This https://github.com/apache/apisix/issues/9528 is an Issue with go grpc library and is fixed here - https://github.com/grpc/grpc-go/issues/6373 / https://github.com/grpc/grpc-go/pull/6374/files. According to this comment, the fix is available in release 1.55.1 - https://github.com/grpc/grpc-go/issues/6373#issuecomment-1624845430 . Our grpc client  nginx module uses version 1.47.0.

**Comment by Sn0rt** [comment]
@AlinsRan pls take a look.

**Comment by AlinsRan** [comment]
LGTM.
We need to adjust the incorrect usage.
